description = 'Rust Programming Language Tutorials'

author = 'Dumindu Madunuwan'
authorURL = 'https://github.com/dumindu'

currentYear = 2023
projectStartYear = 2016

facebookURL = ''
twitterURL = ''
githubURL = 'https://github.com/learning-rust'
youtubeURL = ''

githubRepo = 'learning-rust/site'
githubSponsorURL = 'https://github.com/sponsors/dumindu'
buyMeACoffeeURL = 'https://www.buymeacoffee.com/dumindu'

[algolia]
[algolia.en]
container = '#site-header-search'
appId = 'QEN78N5RTO'
indexName = 'learning_rust'
apiKey = '07315fdb3221618273bdaffb1ab6f388'
